chore(LcBadge): [ch7071] add lc-badge
LeCollectionist/component-library pull request #36
Opened 2021-07-13 10:29 UTC by Flo2315

- Ajout du composant lc-badge
- Ajout des stories
- DOING add test

2021-07-15 14:19 UTC, sbourdon13 commented on src/components/LcBadge/LcBadge.vue
> +  <div :class="['lc-badge', colorClass ? colorClass : 'lc-badge-primary']">
pourquoi ne pas mettre `lc-badge-primary` en valeur par défaut de la props plutôt ? voire même mettre `bg-primary-400 text-primary-700` directement

2021-07-15 14:41 UTC, Flo2315 commented on src/components/LcBadge/LcBadge.vue
> +  <div :class="['lc-badge', colorClass ? colorClass : 'lc-badge-primary']">
Ok pour la mettre en valeur par default 👍 .
Par contre on utilise pas les classes directement dans le HTML, on préfère que les styes soit compilé. pour évité d'avoir des problèmes entre le tailwind de la lib et celui de l'admin (ou autres projets). On peut aussi imaginé que notre librairie soit appeler dans un projet qui n'a pas tailwind et ducoup les classes dans le HTML n'aurons jamais de style.

2021-07-15 15:47 UTC, ClemCornet requested changes

2021-07-15 15:47 UTC, ClemCornet commented on src/components/LcBadge/LcBadge.stories.ts
> +  colorClass: 'bg-secondary-300 text-secondary-500',
Est-ce que tu pourrais rajouter une story avec un args class, pour bien montrer qu'on peut custom le text en lui bindant une class sur le parent :

`export const TextWhite = Template.bind({}) as any
Base.args = {
 class: 'text-white',
}`

2021-07-16 07:34 UTC, ClemCornet approved these changes

2021-07-16 08:40 UTC, sbourdon13 approved these changes

2021-07-16 08:40 UTC, merged